<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="ShoppingHeart.Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Cafe Romma Fremantle || Home</title>
    <link href="css/slicebox.css" rel="stylesheet" type="text/css" />
    <link href="css/animate.min.css" rel="stylesheet" type="text/css" />
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="css/main.css" rel="stylesheet" type="text/css" />
    <link href="css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
        rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->


    <style type="text/css">
        .auto-style1 {
            float: left;
            font-size: x-large;
            line-height: 20px;
            margin: 0;
            padding: 0;
        }

        .auto-style2 {
            color: #456580;
        }
    </style>


</head>
<body>
    <form id="form1" runat="server">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNav">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   
                    <a href="#">
                        <span style="font-size:xx-large; color:#456580">Cafe Romma Fremantle</span></a><a href="Default.aspx" class="navbar-brand">
                        </a>
                </div>
                <div id="myNav" class="collapse  navbar-collapse">
                    <ul class="nav nav-tabs navbar-right">
                        <li><a href="Default.aspx"><span class="fa fa-home"> Home</span></a></li>
                        <li><a href="Index.aspx"><span class="fa fa-search"></span> Our Menu</a></li>
                        <%--<li><a href="AboutUs.aspx"><i class="fa fa-info"></i>About</a></li>--%>
                        <li><a href="ContactUs.aspx"><span class="fa fa-question"></span> Contact Us</a></li>
                        
                    </ul>
                </div>
            </div>
        </div>
        <br />
        <div class="border">
        </div>
        <!-- Start cssSlider.com -->
        <!-- Generated by cssSlider.com 1.9 -->
        <link rel="stylesheet" href="slider/csss_engine1/style.css">
        <!--[if IE]><link rel="stylesheet" href="slider/csss_engine1/ie.css"><![endif]-->
        <!--[if lte IE 9]><script type="text/javascript" src="slider/csss_engine1/ie.js"></script><![endif]-->
        <script type="text/javascript" src="slider/csss_engine1/gestures.js"></script>
        <div class='csslider1 autoplay'>
            <input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide'/>
            <input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide'/>
            <input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide'/>
            <input name="cs_anchor1" id='cs_slide1_3' type="radio" class='cs_anchor slide'/>
            <input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked="checked"/>
            <input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'/>
            <input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'/>
            <input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'/>
            <input name="cs_anchor1" id='cs_pause1_3' type="radio" class='cs_anchor pause'/>
            <ul>
                <li class="cs_skeleton">
                    <img alt="" src="slider/csss_images1/IMG_9044.jpg"
                        style="width: 100%;"/></li>
                <li class='num0 img slide'>
                    <img src='slider/csss_images1/IMG_9052.jpg'
                        alt='abstract-desktop-wallpaper-widescreen-top-model-computers-wallpapers-wallwuzz-hd-wallpaper-10823'
                        title='abstract-desktop-wallpaper-widescreen-top-model-computers-wallpapers-wallwuzz-hd-wallpaper-10823' /></li>
                <li class='num1 img slide'>
                    <img src='slider/csss_images1/IMG_9066.jpg' alt='aura_rays_hd_1080p-HD'
                        title='aura_rays_hd_1080p-HD' /></li>
                <li class='num2 img slide'>
                    <img src='slider/csss_images1/IMG_9068.jpg' alt='qxt1j-wallpapers-515728052-1920x1080'
                        title='qxt1j-wallpapers-515728052-1920x1080' /></li>
                <li class='num3 img slide'>
                    <img src='slider/csss_images1/IMG_9071.jpg' alt='wpid-Abstract-Colorful-Wallpaper-Hd-0'
                        title='wpid-Abstract-Colorful-Wallpaper-Hd-0' /></li>
            </ul>
            
            <div class='cs_play_pause'>
               
                <label class='cs_pause num0' for='cs_pause1_0'>
                    <span><i></i><b></b></span>
                </label>
                <label class='cs_pause num1' for='cs_pause1_1'>
                    <span><i></i><b></b></span>
                </label>
                <label class='cs_pause num2' for='cs_pause1_2'>
                    <span><i></i><b></b></span>
                </label>
                <label class='cs_pause num3' for='cs_pause1_3'>
                    <span><i></i><b></b></span>
                </label>
            </div>

        </div>
        <!-- End cssSlider.com -->


        <section id="section-bar"><br />
        <hr />
        <div class="container" >
            <asp:Label ID="Label1" runat="server" Text=" Please select our Menu Options" Font-Size="Medium"></asp:Label>
            <asp:Panel Width="100%" ID="pnlProducts" runat="server" BackColor="WhiteSmoke" BorderColor="#FEA400" BorderStyle="Inset" BorderWidth="2px" 
                Height="20%" ScrollBars="Auto">
                                                            <asp:DataList ID="dlProducts" runat="server" BackColor="WhiteSmoke" Font-Bold="True" Font-Italic="False" 
                                                                Font-Overline="False" Font-Strikeout="False" Font-Underline="False" FooterStyle-BackColor="WhiteSmoke" 
                                                                FooterStyle-BorderColor="Orange" ForeColor="Green" HeaderStyle-ForeColor="WhiteSmoke" 
                                                                RepeatColumns="5" RepeatDirection="Horizontal" Width="100%" DataSourceID="SqlDataSource1"
                                                                >
                                                                <ItemTemplate>
                                                                    <div align="left">
                                                                        <table cellspacing="0.2" class="style4" style="border: 3px ridge #FEA400">
                                                                            <tr>
                                                                                <td style="border-bottom-style: ridge; border-width: 2px; top:5px; border-color: #FEA400" align="center">
                                                                                    <asp:Label ID="lblProductName" runat="server" ForeColor="Black" Style="font-weight: 700" Text='<%# Eval("Name") %>'></asp:Label>
                                                                                </td>
                                                                            </tr>
                                                                            <tr>
                                                                                <td>
                                                                                    <asp:ImageButton ID="imgBtnProductPhoto" runat="server" ImageUrl='<%# Eval("ImageUrl") %>'  Style="border: ridge 2px #FEA400; width: 220px; height: 250px;" 
                                                                                        OnClick="imgBtnProductPhoto_Click1" />
                                                                                </td>
                                                                            </tr>
                                                                            <tr>
                                                                                <td align="center">Price: $ 
                                                                                    <asp:Label ID="lblPrice" runat="server" ForeColor="Blue" Text='<%# Eval("Price") %>'></asp:Label>
                                                                                    <br />
                                                                                    <asp:Label ID="lblMoney" runat="server" ForeColor="Orange" Text="Perth Only**"></asp:Label>
                                                                                  <%--  <asp:Image ID="imgStar" runat="server" ImageUrl="~/Images/GreenStar.png" Visible="false" />--%>
                                                                                    <br />
                                                                                    
                                                                                    <%--<asp:Label ID="lblAvailableStock" runat="server" Font-Bold="true" ForeColor="Red" Text='<%# Eval("AvailableStock") %>' ToolTip="Available Stock"></asp:Label>--%>
                                                                                   <%-- <asp:Label ID="Label3" runat="server" Font-Bold="true" Text="READY"></asp:Label><br />--%>
                                                                                   <%-- <div class="trustpilot-widget" data-businessunit-id="591a555a0000ff0005a285d8" data-locale="en-AU" data-style-height="52px" data-style-width="100%" data-template-id="56278e9abfbbba0bdcd568bc">
                                                                                        
                                                                                    </div>--%>
                                                                                    <asp:HiddenField ID="hfProductID" runat="server" Value='<%# Eval("ProductID") %>' />
                                                                                </td>
                                                                            </tr>
                                                                            <tr>
                                                                                <td>
                                                                                   <%-- <asp:Button ID="btnAddToCart" runat="server" BackColor="Orange" BorderColor="Black" BorderStyle="Inset" BorderWidth="2px" CausesValidation="false" CommandArgument='<%# Eval("ProductID") %>' Font-Bold="true" ForeColor="White" OnClick="btnAddToCart_Click" Text="Add To Cart" Width="100%" />--%>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </div>
                                                                </ItemTemplate>
                                                                <ItemStyle Width="33%" />
                                                            </asp:DataList>
                                                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ShoppingCartDB1ConnectionString %>" SelectCommand="SELECT TOP (4) PR.ProductID, PR.Name, PR.Price, PR.ImageUrl, PR.CategoryID, PR.ProductQuantity FROM [Products] PR, [CustomerProducts] CPR WHERE PR.ProductID = CPR.ProductID AND PR.ShowHide = 1 AND PR.ProductQuantity > 0 GROUP BY PR.ProductID, PR.Name, PR.Price, PR.ImageUrl, PR.CategoryID, PR.ProductQuantity ORDER BY SUM(CPR.TotalProduct) DESC;"></asp:SqlDataSource>
                                                        </asp:Panel>
        </div>
               
   

            </section>

        <footer id="footer" class="midnight-blue">
        <div class="container ">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2017 <a target="_se0 lf" <%--href="http://aspxtemplates.com/"--%> title="DIGITAL MANIFEST">DIGITAL MANIFEST</a>. All Rights Reserved. </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="Default.aspx"><span class="fa fa-home" style="color:whitesmoke"> Home</span></a></li>
                        <li><a href="Index.aspx"><span class="fa fa-search" style="color:whitesmoke"></span> Our Menu</a></li>
                        <li><a href="AboutUs.aspx"><span class="fa fa-info"  style="color:whitesmoke"></span> About</a></li>
                        <li><a href="ContactUs.aspx"><span class="fa fa-question" style="color:whitesmoke"></span> Contact Us</a></li>
                        <li><a class="auto-style14" href="Admin/Login.aspx" target="_self"><strong>Admin</strong></a></li>
                    </ul>
                    </div>
            </div>
        </div>
        <a href="#" class="back-to-top"><i class="fa fa-2x fa-angle-up"></i></a>
    </footer>
        <!--/#footer-->
        <!-- Back To Top -->
        <script type="text/javascript">
            jQuery(document).ready(function () {
                var offset = 300;
                var duration = 500;
                jQuery(window).scroll(function () {
                    if (jQuery(this).scrollTop() > offset) {
                        jQuery('.back-to-top').fadeIn(duration);
                    } else {
                        jQuery('.back-to-top').fadeOut(duration);
                    }
                });

                jQuery('.back-to-top').click(function (event) {
                    event.preventDefault();
                    jQuery('html, body').animate({ scrollTop: 0 }, duration);
                    return false;
                })
            });
        </script>
        <!-- /top-link-block -->
        <!-- Jscript -->
        <script src="js/jquery.js" type="text/javascript"></script>
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <script src="js/main.js" type="text/javascript"></script>
        <script src="js/wow.min.js" type="text/javascript"></script>
    </form>
</body>
</html>